name = "cformysql-blog"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "7d7f1fb08aaa4703a351120a6d6ab8cb"

[vars]

triggers.crons = ["0 * * * *"]
